### ISSUE TITLE
CI Pipeline to validate PRs

### ISSUE THREAD

**Issue by elamaran11** [aws-observability/cdk-aws-observability-accelerator#31]
**Is your feature request related to a problem? Please describe.**
CI Pipeline to validate PRs

**Describe the solution you'd like**
CI Pipeline to validate PRs

**Describe alternatives you've considered**

**Additional context**

**Comment by shapirov103** [comment]
CI Pipeline is currently implemented with CodeBuild for the following reasons:
1. Does not require refactoring of existing code in order to use patterns in the pipeline
2. No need to come up with a strategy to reuse VPC as currently each pattern is creating a new VPC
3. Allows validating a specific pattern on demand.
4. Merges the PR under review with the main branch and validates that the code after merge successfully runs for a specific pattern.
5. Integrates with the PR flow. 

Configuration that must be applied:

1. AWS Identity (access key) must be added as GitHub secret to trigger the workflow. 
2. GitHub token should be registered as a GitHub repo secret to allow marking PRs with status

Usage:

Add PR comment in this form:

```
/do-e2e-test <PATTERN_NAME>
```

CodeBuild buildspec is part of the repo so it can be expanded to support other tests

**Comment by elamaran11** [comment]
This is merged.
